### PR TITLE
[bug-1079318] - Replace the Kitkat recovery images with Firefox OS version

### PR DESCRIPTION
**Pull request by pivanov**

### CODE REVIEW

**Comment by pivanov** [comment]
@michaelwu can you check this one?

**Comment by michaelwu** [comment]
icon_installing_overlay%02d is hardcoded into recovery, so you cannot append _x1.5 to the names.

Are you able to test these changes locally? Let me know if you need help with that. Doing a factory reset should be an easy way to test a bunch of images.

**Comment by pivanov** [comment]
@michaelwu it will be great if I can test it ... I have a flame .... but I will need help whit this

**Comment by pivanov** [comment]
@michaelwu I just finish testing this one by hand and everything looks good :) what I can do to move this forward?

**Comment by michaelwu** [comment]
Attach the url of this PR to the bugzilla bug (bugzilla should recognize this as a github PR) and request review from me.

**Pull request closed without merging**
